import { Link } from 'gatsby';
import React from 'react';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

const Disclaimer = () => (
  <Container sx={{ p: 5, my: 5, minHeight: 300 }}>
    <Typography variant="h2" sx={{ my: 3 }}>
      Disclaimer
    </Typography>
    <Typography variant="h6">
      Graasp (the &lsquo;software&rsquo;) and its source code are freely
      distributed under the GNU Affero General Public License (AGPLv3). The
      software and source code are provided to you “as is”, without warranty of
      any kind, express or implied. Without limiting the generality of the
      foregoing, the Graasp Association and École Polytechnique Fédérale de
      Lausanne (EPFL) make no representation or warranty regarding the
      functionality, reliability, or performance of the software, or the results
      to be obtained through the use of the software, or that the operation of
      the software shall be error-free. In no event shall the Graasp Association
      or EPFL be liable for any damages arising from the use of Graasp,
      including but not limited to the distribution, misuse, leakage, or theft
      of any original files or datasets or duplicates thereof handled,
      processed, or generated by the software.
    </Typography>

    <Link to="/">
      <Typography variant="h6" sx={{ my: 3 }}>
        Home
      </Typography>
    </Link>
  </Container>
);

export default Disclaimer;
