import { Link } from 'gatsby';
import React from 'react';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

const Terms = () => (
  <Container sx={{ p: 5, my: 5, minHeight: 300 }}>
    <Typography variant="h2" sx={{ my: 3 }}>
      Terms
    </Typography>
    <Typography variant="h6">
      By using Graasp, you: (1) Confirm that you will not misuse the software,
      or help anyone else to do so, (2) Confirm that you will not use the
      software for illicit purposes, (3) Confirm that you are solely responsible
      for the datasets and results handled or generated by the application, (4)
      Accept that the Graasp Association and École Polytechnique Fédérale de
      Lausanne (EPFL) cannot be held liable for any damage resulting from your
      use of the software, including any loss of content and data, and (5)
      Accept that access to the software is provided to you "as is", without any
      warranty, including as to its proper functioning and fitness for a
      particular purpose.
    </Typography>
    <br />
    <Typography variant="h6">
      These Terms of Service are governed by the laws of Switzerland. The legal
      jurisdiction for any dispute shall be in Lausanne, Switzerland. Please
      also refer to the Graasp <Link to="/disclaimer">Legal Disclaimer</Link>{' '}
      and the EPFL websites{' '}
      <a
        href="https://www.epfl.ch/about/overview/regulations-and-guidelines/disclaimer/"
        target="_blank"
        rel="noreferrer"
      >
        disclaimer
      </a>
      .
    </Typography>

    <Link to="/">
      <Typography variant="h6" sx={{ my: 3 }}>
        Home
      </Typography>
    </Link>
  </Container>
);

export default Terms;
