import { Link } from 'gatsby';
import React from 'react';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

const Terms = () => (
  <Container sx={{ p: 5, my: 5, minHeight: 300 }}>
    <Typography variant="h2" sx={{ my: 3 }}>
      Terms
    </Typography>
    <Typography variant="h6">
      By using the Graasp platform and its software, you: (1) Confirm that you
      will not misuse Graasp, or help anyone else to do so, (2) Confirm that you
      will not use Graasp for illicit purposes, (3) Confirm that you are solely
      responsible for the datasets and results handled or generated by Graasp,
      (4) Accept that the Graasp Association and École Polytechnique Fédérale de
      Lausanne (EPFL) cannot be held liable for any damage resulting from your
      use of Graasp, including any loss of content and data, and (5) Accept that
      access to Graasp is provided to you "as is", without any warranty,
      including as to its proper functioning and fitness for a particular
      purpose.
    </Typography>
    <br />
    <Typography variant="h6">
      These Terms of Service are governed by the laws of Switzerland. The legal
      jurisdiction for any dispute shall be Valais (VS), Switzerland. Please
      also refer to the Graasp <Link to="/disclaimer">Legal Disclaimer</Link>{' '}
      and the EPFL websites{' '}
      <a
        href="https://www.epfl.ch/about/overview/regulations-and-guidelines/disclaimer/"
        target="_blank"
        rel="noreferrer"
      >
        disclaimer
      </a>
      .
    </Typography>

    <Link to="/">
      <Typography variant="h6" sx={{ my: 3 }}>
        Home
      </Typography>
    </Link>
  </Container>
);

export default Terms;
