name: Build

on:
  push:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Yarn install and Cache dependencies
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Lint code
        run: yarn lint
        shell: bash

      - name: Yarn build
        # Set environment variables required to perform the build. These are only available to this step
        run: yarn build
        shell: bash
