name: Deploy

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true
        default: dev

jobs:
  deploy-app:
    name: Deploy to (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Yarn install and Cache dependencies
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Yarn build
        # Set environment variables required to perform the build. These are only available to this step
        env:
          GA_MEASUREMENT_ID: ${{ inputs.environment == 'production' && secrets.REACT_APP_GA_MEASUREMENT_ID_PROD || '' }}
        run: yarn build
        shell: bash

      - name: Deploy
        uses: graasp/graasp-deploy/.github/actions/deploy-s3@v1
        # Replace input build-folder or version if needed
        with:
          build-folder: 'dist'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-s3-bucket-name: ${{ vars.AWS_S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ vars.CLOUDFRONT_DISTRIBUTION }}
