name: Deploy

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  deploy-app-to-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Yarn install and Cache dependencies
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Yarn build
        # Set environment variables required to perform the build. These are only available to this step
        env:
          GATSBY_GA_MEASUREMENT_ID: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID_PROD }}
        run: yarn build
        shell: bash

      - name: Deploy
        uses: graasp/graasp-deploy/.github/actions/deploy-s3@v1
        # Replace input build-folder or version if needed
        with:
          build-folder: 'build'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-s3-bucket-name: ${{ vars.AWS_S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ vars.CLOUDFRONT_DISTRIBUTION }}
